### ISSUE TITLE
Can't scroll with keyboard until after tabbing through the header

### ISSUE THREAD

**Issue by br3ndonland** [30-seconds/30-seconds-web#111]
## Issue

I can scroll with the mouse, but not with the keyboard.

macOS 10.15.4, Brave 1.8.95 (Chromium: 81.0.4044.138), Firefox 77.0

- Regular and private browsing
- With and without accepting cookies
- With and without tracker blocking
- No console errors
- Not having this issue on any other websites, with either Brave or Firefox

## Solution

I can't scroll if I click on the page. However, **if I tab through `<header class="nav-bar"` and into `<div class="content">` I am then able to scroll.**

Just wanted to mention this in case anyone is having accessibility issues with the site.

![30seconds-scroll](https://user-images.githubusercontent.com/26674818/81482621-6890ca80-9206-11ea-827a-9ae344c727a5.gif)

Karabiner Elements was used to record keyboard events in the screen recording.

**Comment by Chalarangelo** [comment]
Thanks for informing us. While I always try to provide an accessible UX, this seems to have been overlooked at some point. I'll add it to the list of tasks that I could work on in the next couple of months.

**Comment by br3ndonland** [comment]
Thanks very much. I really appreciate the work you do on 30 seconds. Keep it up!
