### ISSUE TITLE
snippet show on click of anywhere inside snippet card.

### ISSUE THREAD

**Issue by Binu42** [30-seconds/30-seconds-web#115]
currently snippet of particular topic is only showing on click of title of snippet then only route is getting changed.

i think it will be better and easy for users to show snippet on click of anywhere inside the card.

**Comment by Chalarangelo** [comment]
Thanks for the suggestion. After research and testing, we ended up with the title being the only clickable part. There are plans to add other clickable information on the card (or enhance existing information), so we are not going to change this anytime soon.

Cheers!
