### ISSUE TITLE
Enable arrow key navigation on desktop

### ISSUE THREAD

**Issue by ElisabethPlu** [30-seconds/30-seconds-web#149]
Hello !
I've visited your website and I wanted to scroll down the page to read more. I wanted to use the arrow key on my keyboard to to that, as I always do. But it doesn't work. You need to use the mouse to use the scrollbar.
I would like to use the arrow key for scrolling. Maybe it could be a good idea for your website and maybe other people would like it.
Thank you for your website. I will read every posts :)

**Comment by Chalarangelo** [comment]
Thanks for the feedback! This is related to the way the page is rendered with grid. I'll take a look at possible solutions sometime soon.
