### ISSUE TITLE
Link methods, concepts, etc to MDN

### ISSUE THREAD

**Issue by widyakumara** [30-seconds/30-seconds-web#191]
I think it will be beneficial for new programmers to have methods, concepts, etc linked to MDN (or whatever relevant documentation).

E.g. on [Median](https://www.30secondsofcode.org/js/s/median) description have `Array.prototype.sort()` and `length` linked to [Array.prototype.sort()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) and [Array.prototype.length](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/length) on MDN, respectively.

**Comment by Chalarangelo** [comment]
### Update

It's been a while. We are still looking into this feature for the website. It's one of the largest feature requests we have undertaken so far and it relies on external content, so we need to verify that we don't end up with dead links. While the value it provides is pretty significant, it's also very unlikely that we can justify focusing on it right now. So, hold on a bit longer, we'll get around to it when this kind of investment makes more sense for us. 😉
