### ISSUE TITLE
Api for snippets

### ISSUE THREAD

**Issue by DrBeta** [30-seconds/30-seconds-web#194]
Would it be possible to have a api for snippets to integrate into like a app or something?

**Comment by Chalarangelo** [comment]
We currently do not support this. We used to do it in the past, but unfortunately this is deprecated as we want to deliver the best possible UX via the website and be sure that all of our users get a consistent experience, therefore apps and/or other re-implementations of the website are strongly discouraged.

**Comment by DrBeta** [comment]
It would be really convenient to have a menu bar app
