### ISSUE TITLE
Experiment with a caching strategy

### ISSUE THREAD

**Issue by Chalarangelo** [30-seconds/30-seconds-web#270]
- Cache parts of `.content` in development.
- Use git SHAs to cache some content.
- Prefer requirables over extraction, if available.
- See if Travis can cache some data or use stages.
- See if Netlify can cache some data.
- "Seal" some JSON data, such as Dart, Go, C# and PHP, that doesn't change often.

**Comment by Chalarangelo** [comment]
[WeakRef](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef/deref) can be an interesting tool (needs Node 14+) to cache instances during development without consuming too much memory. Let's take a look if it can be of use when implementing this.

**Comment by zaurbey** [comment]
M2d

**Comment by Russeel** [comment]
> - Cache parts of `.content` in development.
> 
> - Use git SHAs to cache some content.
> 
> - Prefer requirables over extraction, if available.
> 
> - See if Travis can cache some data or use stages.
> 
> - See if Netlify can cache some data.
> 
> - "Seal" some JSON data, such as Dart, Go, C# and PHP, that doesn't change often.

**Comment by Chalarangelo** [comment]
#### Update

As we move forward, we're going to revamp the extraction, parsing and serialization strategy to improve development experience. Caching is actively being worked on, but might ultimately be dropped. The new system is significantly more efficient and performant, so caching might not be necessary at all.
