### ISSUE TITLE
Input field is not as per the accessibility and HTML standards

### ISSUE THREAD

**Issue by abhishekrawat22** [30-seconds/30-seconds-web#473]
In HTML, **span** is used to create the prefix for the **input** field, which is **not interactive** if the user wants to focus on the input field when clicking on the prefix text. Also, **accessibility standards** are not followed, like using a **label** for the input with **for** and **id attributes** in the respective element.

**Comment by Chalarangelo** [comment]
`aria-label` is used in place of the label, while the prefix isn't supposed to be clickable.
