### ISSUE TITLE
Provide RSS feed for feed readers

### ISSUE THREAD

**Issue by valentinpalkovic** [30-seconds/30-seconds-web#89]
## Description 
Nowadays there are tons of information out there, that it is really hard to visit websites/blogs one by one to get read all the news around coding. Instead, providing an RSS feed every user can use its very own feed reader to keep up-to-date :)

**Comment by Chalarangelo** [comment]
Hey, @valentinpalkovic! Thanks for the feedback. I transferred the issue to 30-seconds-web, as it is a platform-related task, instead. This might be investigated in Q2 2020, as an enhancement, so hold on while we figure out when and how we will implement it! :wink:

**Comment by Chalarangelo** [comment]
Due to technical issues and the way we generate our content, ordering etc. we will not be implementing this any time soon. I'm closing this for now, but we might revisit this at a later time (maybe Q3 or Q4 2020) and reopen if we find the time to figure it out. Thanks for the suggestion anyways!
